### ISSUE TITLE
Baubles and sachets aren't craftable

### ISSUE THREAD

**Issue by Sunconure11** [HostaPlantain/Floricraft#10]
The baubles from this mod cannot be crafted, and a player of my modpack is reporting that the sachets aren't craftable.

Edit 1: Can confirm they aren't craftable, at least, the specialized ones. In addition, a few of the petals cannot be placed in potpourri (i.e dried sunflowers)

**Comment by HostaPlantain** [comment]
Thank you for playing:) Baubles for MC1.12.2 was not available when I release this mod. This is why Amulets are not craftable. I'll support it soon. However, sachets are craftable and dried sunflower petal"s" are placeable int potpourri.
I will release Floricraft2 before long. Please enjoy Floric Life.
