### ISSUE TITLE
Floricraft-1.12.2-4.4.1 - Amulets

### ISSUE THREAD

**Issue by Iteries** [HostaPlantain/Floricraft#12]
Hello there!  Nice mod but some reason its not working with Baubles in wearing the Amulets..  

Until I can get to wearable bauble.. Do they work within the pack or have to keep it in quick-slots?

**Comment by HostaPlantain** [comment]
Thank you for playing:) Baubles for MC1.12.2 was not available when I release this mod.
I'll support it soon. Please enjoy the Amulets.
