### ISSUE TITLE
Floricraft-1.12.2-4.4.1 - Flower beds Graphics

### ISSUE THREAD

**Issue by Iteries** [HostaPlantain/Floricraft#14]
MC: 1.12.2
Forge: -2577
Opt: HD-C8

Hello, been playing with your mod and I do love it.  Wonderful ideas and creativity.  However, still a few bugs to wrinkle out.  This one being the Flower Beds in flashing invisible at certain angles, especially when in 2 flowers that are 2-heights.  Not sure why it does this either.  Could be Opt,, Forge or just something of the code in the mod for appearances.

**Comment by HostaPlantain** [comment]
Flashing with 2 2-hights flowers is caused by my code. 2 flowers were too close. I'll fix it.
If flowers are still invisible at certain angles, it should be caused by vanilla Minecraft. You need to see the block body to render the block.
